Test that old protocols are not supported
=========================================

ZEO5 client used to support both ZEO5 and ZEO4 servers. Later support for
ZEO5.client-ZEO4.server interoperability was found to be subject to data
corruptions and removed. Here we verify that current ZEO client rejects
connecting to old ZEO server.

Let's start a Z4 server

    >>> storage_conf = '''
    ... <filestorage>
    ...    path Data.fs
    ... </filestorage>
    ... '''

    >>> addr, stop = start_server(
    ...    storage_conf, {'msgpack': 'false'}, protocol=b'4')

A current client should not be able to connect to an old server:

    >>> import ZEO, logging, zope.testing.loggingsupport
    >>> hlog = zope.testing.loggingsupport.InstalledHandler(
    ...     'ZEO.asyncio.client', level=logging.ERROR)
    >>> logging.getLogger('ZEO.asyncio.client').addHandler(hlog)
    >>> ZEO.client(addr, client='client', wait_timeout=2)
    Traceback (most recent call last):
      ...
    ClientDisconnected: timed out waiting for connection

    >>> print(hlog)
    ZEO.asyncio.client ERROR
      Registration or cache validation failed, b'Z4'

    >>> hlog.uninstall()
